export type TimezoneOption = {
    offset: string;
    market: string;
    value: string;
    label: string;
};

const buildTimezoneOption = (offset: string, market: string): TimezoneOption => ({
    offset,
    market,
    value: `(${offset}) ${market}`,
    label: `(${offset}) ${market}`,
});

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
    buildTimezoneOption("UTC", "Mercado bursatil"),
    buildTimezoneOption("UTC-10", "Honolulu"),
    buildTimezoneOption("UTC-8", "Anclaje"),
    buildTimezoneOption("UTC-8", "Juneau"),
    buildTimezoneOption("UTC-7", "Los Angeles"),
    buildTimezoneOption("UTC-7", "Phoenix"),
    buildTimezoneOption("UTC-7", "Vancouver"),
    buildTimezoneOption("UTC-6", "Ciudad de Mexico"),
    buildTimezoneOption("UTC-6", "Denver"),
    buildTimezoneOption("UTC-6", "San Salvador"),
    buildTimezoneOption("UTC-5", "Bogota"),
    buildTimezoneOption("UTC-5", "Chicago"),
    buildTimezoneOption("UTC-5", "Lima"),
    buildTimezoneOption("UTC-4", "Caracas"),
    buildTimezoneOption("UTC-4", "Nueva York"),
    buildTimezoneOption("UTC-4", "Toronto"),
    buildTimezoneOption("UTC-3", "Buenos Aires"),
    buildTimezoneOption("UTC-3", "Halifax"),
    buildTimezoneOption("UTC-3", "Santiago"),
    buildTimezoneOption("UTC-3", "Sao Paulo"),
    buildTimezoneOption("UTC-1", "Azores"),
    buildTimezoneOption("UTC", "Casablanca"),
    buildTimezoneOption("UTC", "Dublin"),
    buildTimezoneOption("UTC", "Lisboa"),
    buildTimezoneOption("UTC", "Londres"),
    buildTimezoneOption("UTC", "Reikiavik"),
    buildTimezoneOption("UTC+1", "Amsterdam"),
    buildTimezoneOption("UTC+1", "Belgrado"),
    buildTimezoneOption("UTC+1", "Berlin"),
    buildTimezoneOption("UTC+1", "Bratislava"),
    buildTimezoneOption("UTC+1", "Bruselas"),
    buildTimezoneOption("UTC+1", "Budapest"),
    buildTimezoneOption("UTC+1", "Copenhague"),
    buildTimezoneOption("UTC+1", "Estocolmo"),
    buildTimezoneOption("UTC+1", "Lagos"),
    buildTimezoneOption("UTC+1", "Ljubljana"),
    buildTimezoneOption("UTC+1", "Luxemburgo"),
    buildTimezoneOption("UTC+1", "Madrid"),
    buildTimezoneOption("UTC+1", "Malta"),
    buildTimezoneOption("UTC+1", "Oslo"),
    buildTimezoneOption("UTC+1", "Paris"),
    buildTimezoneOption("UTC+1", "Praga"),
    buildTimezoneOption("UTC+1", "Roma"),
    buildTimezoneOption("UTC+1", "Tunez"),
    buildTimezoneOption("UTC+1", "Varsovia"),
    buildTimezoneOption("UTC+1", "Viena"),
    buildTimezoneOption("UTC+1", "Zagreb"),
    buildTimezoneOption("UTC+1", "Zurich"),
    buildTimezoneOption("UTC+2", "Atenas"),
    buildTimezoneOption("UTC+2", "Bucarest"),
    buildTimezoneOption("UTC+2", "Cairo"),
    buildTimezoneOption("UTC+2", "Helsinki"),
    buildTimezoneOption("UTC+2", "Jerusalen"),
    buildTimezoneOption("UTC+2", "Johannesburgo"),
    buildTimezoneOption("UTC+2", "Nicosia"),
    buildTimezoneOption("UTC+2", "Riga"),
    buildTimezoneOption("UTC+2", "Sofia"),
    buildTimezoneOption("UTC+2", "Tallin"),
    buildTimezoneOption("UTC+2", "Vilnius"),
    buildTimezoneOption("UTC+3", "Bahrein"),
    buildTimezoneOption("UTC+3", "Catar"),
    buildTimezoneOption("UTC+3", "Estambul"),
    buildTimezoneOption("UTC+3", "Kuwait"),
    buildTimezoneOption("UTC+3", "Moscu"),
    buildTimezoneOption("UTC+3", "Nairobi"),
    buildTimezoneOption("UTC+3", "Riad"),
    buildTimezoneOption("UTC+3:30", "Teheran"),
    buildTimezoneOption("UTC+4", "Dubai"),
    buildTimezoneOption("UTC+4", "Muscat"),
    buildTimezoneOption("UTC+4:30", "Kabul"),
    buildTimezoneOption("UTC+5", "Asjabad"),
    buildTimezoneOption("UTC+5", "Astana"),
    buildTimezoneOption("UTC+5", "Karachi"),
    buildTimezoneOption("UTC+5:30", "Calcuta"),
    buildTimezoneOption("UTC+5:30", "Colombo"),
    buildTimezoneOption("UTC+5:45", "Katmandu"),
    buildTimezoneOption("UTC+6", "Dhaka"),
    buildTimezoneOption("UTC+6:30", "Yangon"),
    buildTimezoneOption("UTC+7", "Bangkok"),
    buildTimezoneOption("UTC+7", "Ho Chi Minh"),
    buildTimezoneOption("UTC+7", "Yakarta"),
    buildTimezoneOption("UTC+8", "Chongqing"),
    buildTimezoneOption("UTC+8", "Hong Kong"),
    buildTimezoneOption("UTC+8", "Kuala Lumpur"),
    buildTimezoneOption("UTC+8", "Manila"),
    buildTimezoneOption("UTC+8", "Perth"),
    buildTimezoneOption("UTC+8", "Shanghai"),
    buildTimezoneOption("UTC+8", "Singapur"),
    buildTimezoneOption("UTC+8", "Taipei"),
    buildTimezoneOption("UTC+9", "Seul"),
    buildTimezoneOption("UTC+9", "Tokio"),
    buildTimezoneOption("UTC+10", "Brisbane"),
    buildTimezoneOption("UTC+10:30", "Adelaida"),
    buildTimezoneOption("UTC+11", "Sidney"),
    buildTimezoneOption("UTC+12", "Isla de Norfolk"),
    buildTimezoneOption("UTC+13", "Nueva Zelanda"),
    buildTimezoneOption("UTC+13", "Tokelau"),
    buildTimezoneOption("UTC+13:45", "Islas Chatham"),
];

